### ISSUE TITLE
NUSGrabberGUI has stopped working.

### ISSUE THREAD

**Issue by pittjosh81** [FoxMcloud5655/NEW-NUSGrabberGUI#7] opened 2016-11-24 03:25 UTC
When I launch the program, it says connecting to Internet, then parsing data, and then the program crashes. I have installed the x86 distribution, and all the required files are in the directory.

Can you help me? What more information do you need? I'm running Windows 7 Ultimate.

**Comment by FoxMcloud5655** [comment] 2016-11-28 16:45
Can you provide a debug report?  What happens when the program crashes?  Does it immediately exit?

**Comment by rjxs** [comment] 2016-12-30 02:31
Hi, I'm having the same exact problem. I tried renaming it as you said in your post on gbatemp.

It opens seemingly fine, and then about a second after it says "parsing data" it crashes immediately and gives a generic error message. I made sure to install the x86 version of the visual c++, and upon seeing a later post in the thread I tried deleting the two .dll files that start with "m"

Thank you for making this program even if I haven't been able to get it to run yet.

**Comment by FoxMcloud5655** [comment] 2017-01-13 14:17
You're welcome :)  I'm trying my best here.  Let's see the "debug.log" that the program created when you put it in debug mode by renaming the program.

**Comment by okisub** [comment] 2017-01-15 21:58
![grabber](https://cloud.githubusercontent.com/assets/25139609/21966553/40212396-dbc1-11e6-9466-2ed5fb8e8b4e.JPG)

I am getting the same error as well.  I have attached a screenshot and pasted the debug file produced by the program below:



NEW-NUSGrabberGUI v0.89 beta started in emulated debug mode on 16/01/2017 7:58:01 AM

16/01/2017 7:58:01 AM - Completed load successfully.
16/01/2017 7:58:01 AM - Connecting to http://wiiubrew.org/wiki/Title_database.
16/01/2017 7:58:02 AM - Parsing data gathered from http://wiiubrew.org/wiki/Title_database.
16/01/2017 7:58:05 AM - Cleaning up unneeded resource: E:\wiiu\CDecrypt.exe.
16/01/2017 7:58:05 AM - Cleaning up unneeded resource: E:\wiiu\msvcr120.dll.
16/01/2017 7:58:05 AM - Cleaning up unneeded resource: E:\wiiu\msvcp140.dll.
16/01/2017 7:58:05 AM - Cleaning up unneeded resource: E:\wiiu\libeay32.dll.
16/01/2017 7:58:05 AM - Cleaning up unneeded resource: E:\wiiu\NUSgrabber.exe.
16/01/2017 7:58:05 AM - Cleaning up unneeded resource: E:\wiiu\vcruntime140.dll.
16/01/2017 7:58:05 AM - Cleaning up unneeded resource: E:\wiiu\wget.exe.
16/01/2017 7:58:05 AM - Preforming shut down process.

**Comment by HoDANG** [comment] 2017-01-15 22:57
Same error as @okisub 
Same debug.log as @okisub

**Comment by theboy181** [comment] 2017-01-15 23:11
Just started getting this too.. Any chance the rest of you have Cemu 1.7.0c installed? 
What are the possible solutions to try ?

**Comment by okisub** [comment] 2017-01-15 23:15
Cemu not installed here.

**Comment by theboy181** [comment] 2017-01-15 23:21
Looks like wiiubrew.org is down http://downuptime.net/wiiubrew.org.html I'm wondering if this has something to do with it.

**Comment by theboy181** [comment] 2017-01-15 23:47
How do I get New-NUSGrabber into debug mode? 
Also I am unable to install Visual C++ Redistributable for Visual Studio 2015 
[1DBC:25E4][2017-01-15T15:52:38]e000: Error 0x80070666: Cannot install a product when a newer version is installed.

Is 2015 needed or will the greater version run. Kinda stumped as I haven't changed anything.

**Comment by theboy181** [comment] 2017-01-16 01:38
Issue was related to the website  not working.. You may want to change the error to avoid confusion in the future.

**Comment by stephenjayakar** [comment] 2017-03-01 07:18
I'm having the same problem, and no debug.log is created.  A bunch of files are created when I open the program, but disappear when I close it.

**Comment by Toranekochan** [comment] 2017-03-01 14:33
Same here, except when i re-downloaded and unzipped it an entire folder was missing. The other file still reappear and disappear however. When i try to copy the files that appear and disappear, they end up getting deleted once the program "stopped working" error has come up and gives me no other choice but to close the program.

**Comment by ParisJWeaver** [comment] 2017-03-02 02:38
I'm having the same problem @FoxMcloud5655 are you still working on a solution?

**Comment by FoxMcloud5655** [comment] 2017-03-02 14:49
I'm not working on a solution actively, as I have a lot of other coding projects at work that I must complete.  Believe me, though, I'm very aware of this issue, and I'm still not sure what causes it. Personally, everything works on every system that I've tested it on, but it's hard to fix an error using my systems when I can't actually reproduce the error!  However, with the current version, I do know that the generalized error that's not being handled is the reason why the program crashes after attempting to parse the data.

All of that to say, I'm aware of this issue, and I'm not 100% sure how to fix it, but I'm going to try my best, even though I have a lot to get done at work.

**Comment by Krakn3dfx** [comment] 2017-03-02 20:37
This looks to be something server side, not with the app itself, guessing probably related to this Breath of the Wild release.

**Comment by ghost** [comment] 2017-03-03 21:09
I have the exact same issue. But, could you provide an earlier compiled version of the program that might not have this error?

**Comment by CJX3M** [comment] 2017-03-04 23:43
Well, glad to know I'm not the only one with this problem

**Comment by CJX3M** [comment] 2017-03-05 00:53
From what I checked, the problem happens when parsing this table row

![image](https://cloud.githubusercontent.com/assets/5133204/23583469/243bfd8a-010b-11e7-9ade-ee62472e2c40.png)

Versions info comes in columncount 4, not 6, so when checking the version is 0 to add to GameUpdate list, is crashess with a NullException

![image](https://cloud.githubusercontent.com/assets/5133204/23583480/a510f866-010b-11e7-9bc7-4d909a7d4094.png)

I added a `|| columncount == 4` but I don't think that was enough, as all the interface was completely disabled and I don't have the time to keep debugging, but I hope this help to solve it

**Comment by ghost** [comment] 2017-03-06 20:43
@CJX3M So you're saying that when this row is parsed, it crashes with this error? And if so, do you think it will work to completely remove it?

**Comment by lemuee** [comment] 2017-03-11 19:59
It seems to me that the wrong table is parsed. Instead of `0005001B: System Data Archive Titles` it should be `00050000: eShop and disc titles` where the version info comes in columncount 6.

Replacing `case 4` with `case 7` in `switch (tablecount)` worked for me.

**Comment by FoxMcloud5655** [comment] 2017-03-13 11:56
A simple change found relatively easily!  I would have done it myself, but
the problem is that I've been sick (still am) for the past week+.  If one
of you guys want to make the change and request a merge, I can at least
look over the code and provide an "official" hotfix for everyone.

**Closed as completed** 2017-03-13 14:59 UTC

**Comment by Parzival-7235** [comment] 2022-11-27 06:31
@FoxMcloud5655, I see @lemuee fixed the issue but I cant figure out where he replaces those lines. Can you offer some clarification?

**Comment by FoxMcloud5655** [comment] 2022-11-27 15:44
The change has already been integrated in pull request #14.
